#include<stdalign.h>
#include<stdlib.h>
#include<math.h>

int main(){
   int Xa,Xb,Ya,Yb,K1,K2;
   int p,g;

   printf("Pls enter the value of p and g that should be primitive roots !!!\n");

   printf("\nEnter the prime number p : ");
   scanf("%d", &p);
   printf("\nEnter the value of g : ");
   scanf("%d",&g);
   printf("\nEnter the selected private key by alice (Xa): ");
   scanf("%d",&Xa);
   printf("\nEnter the selected private key by Bob (Xb): ");
   scanf("%d",&Xb);


   Ya = (int)pow(g,Xa)%p;
   printf("The Secret key for alice is : %d\n",Ya);

   Yb = (int)pow(g,Xb)%p;
   printf("The Secret key for Bob is : %d\n",Yb);

   K1 = (int)pow(Yb,Xa)%p;
   printf("The key generate by alice is : %d\n",K1);

   K2 = (int)pow(Ya,Xb)%p;
   printf("The key generate by bob is : %d\n",K2);


   if(K1 == K2){
       printf("Both keys generated by alice and bob is similier so key exchange is successful...");
   } else
   {
       printf("Both keys generated by alice and bob is not same so key exchange is failed...");

   }

}